// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MondayDemo.Api;

#nullable disable

namespace MondayDemo.Api.Migrations
{
    [DbContext(typeof(ChoreContext))]
    [Migration("20240923091915_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MondayDemo.Api.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MyProperty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Wash the dishes in the sink",
                            IsDone = false,
                            Title = "Do the dishes"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Take the dog for a walk around the block",
                            IsDone = false,
                            Title = "Walk the dog"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Go to the store and buy groceries for the week",
                            IsDone = false,
                            Title = "Buy groceries"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
